# Generated by Django 3.2.9 on 2021-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opendata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocean', models.CharField(default='none', max_length=80)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('area1', models.CharField(max_length=80, null=True)),
                ('area2', models.CharField(max_length=80, null=True)),
                ('area3', models.CharField(max_length=80, null=True)),
                ('area4', models.CharField(max_length=80, null=True)),
                ('temp', models.FloatField(default=0)),
                ('oxy', models.FloatField(default=0)),
                ('ph', models.FloatField(default=0)),
                ('salt', models.FloatField(default=0)),
                ('turb', models.FloatField(default=0)),
                ('obs_date', models.DateField()),
                ('obs_time', models.TimeField()),
            ],
        ),
    ]
