# Generated by Django 3.2.9 on 2021-12-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opendata',
            old_name='turb',
            new_name='ntu',
        ),
    ]
