# Generated by Django 3.2.9 on 2022-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211224_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='ntu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='oxy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='salt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
