# Generated by Django 3.2.9 on 2022-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='crc',
            field=models.IntegerField(),
        ),
    ]
