# Generated by Django 3.2.9 on 2022-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoy', '0002_alter_data_crc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='crc',
            field=models.CharField(max_length=100),
        ),
    ]
