# Generated by Django 3.2.9 on 2022-05-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buoy', '0003_alter_data_crc'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='buoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buoy.buoy'),
        ),
    ]
